# Generated by Django 4.0.2 on 2022-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
