# Generated by Django 4.0.2 on 2022-02-23 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
