# Generated by Django 4.0.2 on 2022-02-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_amount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ingredients', serialize=False, to='recipes.ingredient'),
        ),
    ]
