# Generated by Django 4.0.2 on 2022-02-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_code',
            new_name='color',
        ),
    ]
